### PR TITLE
feat: show date when next show more than 24h away

### PR DESCRIPTION
**Pull request by alyxbb**

### CODE REVIEW

**Comment by Keeeeeeeen** [comment]
Looks good, though with this lengthening the text, it can lead to some spill over onto the next line (see Coming Up)
image
Maybe it'd be worth looking into some better spillover handling? (I.e. lowering font size to keep on same line?) it's a minor edgecase and not really the jurisdiction of this PR, but came to mind

**Comment by ashhhleyyy** [comment]
maybe if the date is >7d, show just "6th september", otherwise just show "friday"?

**Comment by Keeeeeeeen** [comment]
That does seem like a good move to me

**Comment by alyxbb** [comment]
it now shows:

- the day of week if between 1 and 6 days
- the date and day of week if between 6 and 27 days
- the date, month and day of week if over 27 days
- the hour if less than 24 h

I chose 6 and 27 days as it means that for example if there is a show at 9am on a friday and the show before is 7pm on a friday, timelord saying "09:00 friday" is unintutive

**Review by ashhhleyyy — APPROVED** [review]

**Comment by ashhhleyyy** [comment]
I also noticed today, it's probably worth porting something like this to 2016-site, which is currently showing this:
image
(jukebox ends at 5pm **tomorrow**, which is not indicated)
this will need to be implemented in both the JS that updates that box, and in the go logic (i'll open an issue)

**Pull request merged**
